### ISSUE TITLE
Bug - Eorðtilia Belt/Onion

### ISSUE THREAD

**Issue by DrunkTaank** [DasSauerkraut/Terraheim#13]
Not sure if it is intended or not, but the effect of the Eorðtilia Belt does not proc when harvesting onions or seed onions.

**Comment by wonkotron** [comment]
"onion" is missing from the isCrop check function.

Relevant function:
https://github.com/DasSauerkraut/Terraheim/blob/2ffd6986373b5f0e4f9d46193446f2b057b2a26b/Patches/PickableDropPatch.cs#L46-L62

**Comment by raulcanales** [comment]
Is it possible to get this in? I came here also to see if I could fix it, then I stumbled on [this PR ](https://github.com/DasSauerkraut/Terraheim/pull/14) that seems to fix it :)

**Comment by DrunkTaank** [comment]
> 

Tell me about it.  I've even posted in the mod author's discord server that the fix is pending.  Still waiting...

**Comment by DasSauerkraut** [comment]
Fixed in v2.3.0
