### ISSUE TITLE
Code License?

### ISSUE THREAD

**Issue by zirconstorm** [DasSauerkraut/Terraheim#17]
Per the Nexus Mods page, we are allowed to copy and/or modify any files in this project as long as we credit you as the author of the original mod. However, that licensing does not appear in this GitHub repo. Could you please update the licensing information for this project so others could pick up the development and maintenance of this mod? Thanks!

![image](https://user-images.githubusercontent.com/60073582/158521329-50b49f11-3a2e-41a8-b501-6bccc9680259.png)

**Comment by DasSauerkraut** [comment]
Added the GNU public licence
